import {
  Home,
  Truck,
  FileText,
  Bell,
  User,
  Search,
  Plus,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  MapPin,
  Clock,
  ArrowRight,
  Check,
  CheckCircle2,
  X,
  Calendar,
  Send,
  Eye,
  AlertTriangle,
  MoreHorizontal,
  Filter,
  Gauge,
  Wrench,
  Route,
  DollarSign,
  Settings,
  Box,
  Link2,
  Copy,
  Fuel,
  Phone,
  LayoutGrid,
  Users,
  Receipt,
  BarChart3,
  Building2,
  Shield,
  Lock,
  CreditCard,
  Plug,
  LogOut,
  Pencil,
  Download,
  Sparkles,
  TrendingUp,
  Share,
  type LucideIcon,
} from 'lucide-react-native';
import { useTheme } from '@/theme/ThemeProvider';

// Maps the design's icon vocabulary (feather/lucide line style, ~1.7 stroke,
// rounded joins) to the Lucide RN set. Keys match the design's TWIcons names.
export const icons = {
  home: Home,
  truck: Truck,
  file: FileText,
  bell: Bell,
  user: User,
  search: Search,
  plus: Plus,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  pin: MapPin,
  clock: Clock,
  arrowRight: ArrowRight,
  check: Check,
  checkCircle: CheckCircle2,
  x: X,
  share: Share,
  calendar: Calendar,
  send: Send,
  eye: Eye,
  alert: AlertTriangle,
  more: MoreHorizontal,
  filter: Filter,
  gauge: Gauge,
  wrench: Wrench,
  route: Route,
  dollar: DollarSign,
  settings: Settings,
  box: Box,
  link: Link2,
  copy: Copy,
  fuel: Fuel,
  phone: Phone,
  grid: LayoutGrid,
  users: Users,
  receipt: Receipt,
  chart: BarChart3,
  building: Building2,
  shield: Shield,
  lock: Lock,
  card: CreditCard,
  plug: Plug,
  logout: LogOut,
  edit: Pencil,
  download: Download,
  sparkle: Sparkles,
  trend: TrendingUp,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({
  name,
  size = 22,
  color,
  strokeWidth = 1.7,
}: {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
}) {
  const { colors } = useTheme();
  const Cmp = icons[name];
  return <Cmp size={size} color={color ?? colors.fg} strokeWidth={strokeWidth} />;
}
